config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'homes/about' => 'homes#about', as: 'about'
  resources :users
  resources :books, except:[:new] do
    resources :favorites, only:[:create, :destroy]
    resources :comments, only:[:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  attachment :profile_image
  
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:top]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :set_book, only:[:show, :edit, :update]
  
  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    book.save
    redirect_to books_path
  end
  
  def index
    @book = Book.new
    @books = Book.all
  end
  
  def show
    @comment = Comment.new
    @comments = Comment.where(book_id: params[:id])
  end
  
  def edit
  end
  
  def update
    @book.update(book_params)
    redirect_to books_path(params[:id])
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def set_book
    @book = Book.find(params[:id])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    comment.book_id = params[:book_id]
    comment.user_id = current_user.id
    comment.save
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    user = current_user
    book = Book.find(params[:book_id])
    Favorite.create(user_id: user.id, book_id: book.id)
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    user = current_user
    book = Book.find(params[:book_id])
    favorite = Favorite.find_by(user_id: user.id, book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @books = Book.where(user_id: params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to users_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= form_with model:@book, local:true do |f| %>
<%= f.text_field :title %>
<%= f.text_area :body %>
<%= f.submit %>
<% end %>

<%= link_to 'Back', :back %>

app/views/books/index.html.erb
<h1>投稿</h1>
<%= form_with model:@book, local:true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>投稿者</th>
      <th>タイトル</th>
      <th>感想</th>
      <th></th>
      <th>いいね数</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "20190916_230848.jpg", size: "40x40" %></td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td>
        <% if book.favorited_by?(current_user) %>
          <%= link_to book_favorite_path(book.id, book.id), method: :delete do %>
            ♥
          <% end %>
        <% else %>
          <%= link_to book_favorites_path(book.id), method: :post do %>
            ♡
          <% end %>
        <% end %>
      </td>
      <td><%= book.favorites.count %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<h1>book detail</h1>
  <%= @book.title %>
  <%= @book.body %>
  <%= link_to '編集', edit_book_path(@book.id) %>
  <%= link_to '削除', book_path(@book.id), method: :delete %>

<h1>コメント一覧</h1>
  <table>
    <thead>
      <tr>
        <th>投稿者</th>
        <th>コメント</th>
      </tr>
    </thead>
    <tbody>
      <% @comments.each do |comment| %>
      <tr>
        <td>
          <%= attachment_image_tag comment.user, :profile_image, format: 'jpeg', fallback: "20190916_230848.jpg", size: "40x40" %><br>
          <%= comment.user.name %>
        </td>
        <td><%= comment.comment %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

<h3>コメント投稿</h3>
  <%= form_with model:@comment, url:book_comments_path(@book.id), local:true do |f| %>
  <%= f.text_field :comment %>
  <%= f.submit 'コメント投稿！' %>
  <% end %>

app/views/homes/about.html.erb
<h1>紹介ページ！！</h1>

app/views/homes/top.html.erb
<h1>トップページ！！</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <%= link_to 'top', root_path %>
        <%= link_to 'books', books_path %>
        <%= link_to 'users', users_path %>
        <%= link_to 'log_out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'about', about_path %>
        <%= link_to 'log_in', user_session_path %>
        <%= link_to 'sign_up', new_user_registration_path %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>User/edit</h1>

<%= form_with model:@user, local:true do |f| %>
  <%= f.text_field :name %>
  <%= f.attachment_field :profile_image %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>投稿者</th>
      <th>投稿件数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "20190916_230848.jpg", size: "40x40" %></td>
      <td><%= link_to user.name, user_path(user.id) %></td>
      <td><%= link_to "#{user.books.count}件", user_path(user.id) %></td>
      <td><%= link_to "編集", edit_user_path(user) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>user/showページ</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>感想</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>